name: breast_cancer_detection
description: A Flutter app for breast cancer detection using AI technology

publish_to: 'none'

version: 4.0.5+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # HTTP and API
  http: ^1.1.0
  
  # State management
  provider: ^6.0.5
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Image handling
  image_picker: ^1.0.4
  
  # Utils
  intl: ^0.20.2
  
  # Sharing functionality
  url_launcher: ^6.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#E91E63"
    theme_color: "#E91E63"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
